package com.money_hunter.domain;

public enum AdEventType {
	AUTO_HUNT,
	SKILL_POINT,
	REWARD_CLAIM,
	FRIEND_INVITE_REWARD,
	DORMANT_SP_REWARD,
	DUNGEON_COUPON,
	DUNGEON_ADDITIONAL_ENTRY,
	DUNGEON_RUN,
	BOSS_RAID
}
