package com.money_hunter.domain;

public enum SkillType {
	STRENGTH,
	DEXTERITY,
	INTELLIGENCE,
	LUCK,
	MINING_MASTERY,
	RAPID_ATTACK,
	REWARD_AMPLIFIER,
	AUTO_HUNT_EFFICIENCY,
	PET_FLARE_ATTACK,
	PET_AQUA_ATTACK
}
