services:
  money-hunter-postgres:
    image: postgres:16-alpine
    container_name: money-hunter-postgres
    environment:
      POSTGRES_DB: money_hunter_local
      POSTGRES_USER: money_hunter
      POSTGRES_PASSWORD: money_hunter
    ports:
      - "15432:5432"
    volumes:
      - money-hunter-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U money_hunter -d money_hunter_local"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  money-hunter-postgres-data:
