package com.money_hunter.application.dto.response;

import java.time.Instant;
import java.util.List;

import com.money_hunter.domain.JobType;

public record PlayerStateResponse(
		String userKey,
		String gameProfileNickname,
		JobType job,
		boolean onboardingRequired,
		boolean tutorialRewardClaimed,
		boolean featureTutorialRequired,
		int characterSlots,
		int maxCharacterSlots,
		int companionPriceWon,
		long petSkinPriceGold,
		List<String> ownedPetSkinKeys,
		String petOneSkinKey,
		String petTwoSkinKey,
		int skillPointPackPriceWon,
		int skillPointPackAmount,
		long gold,
		long cumulativeGoldEarned,
		long rewardGoldThreshold,
		int rewardPointAmount,
		int adRevenuePerRewardAdWon,
		int goldPerTossPoint,
		int payoutRatePercent,
		int rewardProgressPercent,
		boolean rewardClaimable,
		int skillPoints,
		boolean skillPointRewardsAvailable,
		Instant nextAutoHuntAdAvailableAt,
		Instant nextBoostAdAvailableAt,
		Instant nextSkillPointAdAvailableAt,
		long autoHuntAdSeconds,
		long boostAdSeconds,
		long maxAdSeconds,
		int friendInviteRewardCount,
		int friendInviteLimit,
		int friendInviteRewardSkillPoints,
		int level,
			long experience,
			int nextLevelExperience,
			long goldPerHour,
			long baseGoldPerHour,
			long boostedGoldPerHour,
			int attackIntervalMillis,
			int normalAttackIntervalMillis,
			int boostedAttackIntervalMillis,
			Instant autoHuntEndsAt,
			Instant boostEndsAt,
		MonsterResponse monster,
		List<SkillResponse> skills,
		NotificationResponse latestNotification
) {
}
